### ISSUE TITLE
'objectName' in SecretProviderClass yaml should be secret arn?

### ISSUE THREAD

**Issue by Johnsonkdavid** [waswani/eks-secrets-manager#1]
I got an access denied error while fetching the secrets when I pass objectName as my secret name. Later I changed that to the secret arn and that issue got fixed.

https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-2:[111122223333]:secret:MySecret-00AACC"
          jmesPath: 
              - path: username
                objectAlias: dbusername
              - path: password
                objectAlias: dbpassword
        - objectName: "arn:aws:secretsmanager:us-east-2:[111122223333]:secret:MySecret2-00AABB"
        - objectName: "MySecret3"
          objectType: "secretsmanager"
        - objectName: "MySecret4"
          objectType: "secretsmanager"
          objectVersionLabel: "AWSCURRENT"
```
